"""
web_search.py — Sanju AI
Web search + page summarization. Search results come from DuckDuckGo via
the `ddgs` package (no API key needed); the summary is generated by your
local Ollama model, so this feature stays free and key-free end to end —
it just needs an internet connection for the search/fetch step.

Install:
    pip install ddgs beautifulsoup4 requests
    # NOTE: `duckduckgo_search` was renamed to `ddgs` — if you still have
    # the old package installed, `pip uninstall duckduckgo_search` first.
"""

import re
import requests
import urllib3
from bs4 import BeautifulSoup
from ddgs import DDGS
import model_manager

# Closer to what an actual browser sends — a bare User-Agent alone is an
# easy bot-detection signal, and several sites (anydesk.com among them)
# 403 requests that look automated. This won't get past everything, but
# it clears a lot of basic bot-blocking that a single header didn't.
HEADERS = {
    "User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",
}
MAX_RESULTS    = 3      # how many pages to pull in
MAX_PAGE_CHARS = 3000    # per-page character cap sent to the model


def _ddg_search(query: str, max_results: int = MAX_RESULTS) -> list[dict]:
    try:
        with DDGS() as ddgs:
            return list(ddgs.text(query, max_results=max_results))
    except Exception as e:
        print(f"[WebSearch] Search error: {e}")
        return []


def _fetch_page_text(url: str) -> str:
    try:
        resp = requests.get(url, headers=HEADERS, timeout=6)
        resp.raise_for_status()
    except requests.exceptions.SSLError:
        # "self-signed certificate in certificate chain" almost always
        # means something LOCAL is intercepting HTTPS — antivirus (Kaspersky,
        # Avast, etc.) or a corporate proxy doing SSL inspection — not an
        # actual attack on this connection. Retrying once without cert
        # verification is a reasonable trade-off here since this is
        # read-only text scraping for a summary, not sending credentials.
        # (If you want this fully verified, check your antivirus's "HTTPS
        # scanning" / "SSL inspection" setting — turning it off for this
        # traffic is the real fix.)
        try:
            urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
            resp = requests.get(url, headers=HEADERS, timeout=6, verify=False)
            resp.raise_for_status()
        except Exception as e:
            print(f"[WebSearch] Fetch error for {url} (SSL retry failed): {e}")
            return ""
    except Exception as e:
        print(f"[WebSearch] Fetch error for {url}: {e}")
        return ""

    try:
        soup = BeautifulSoup(resp.text, "html.parser")
        for tag in soup(["script", "style", "nav", "footer", "header", "noscript"]):
            tag.decompose()
        text = re.sub(r"\s+", " ", soup.get_text(separator=" ")).strip()
        return text[:MAX_PAGE_CHARS]
    except Exception as e:
        print(f"[WebSearch] Parse error for {url}: {e}")
        return ""


def _strip_think(text: str) -> str:
    return re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()


def search_and_summarize(query: str) -> str:
    """
    Searches the web for `query`, pulls text from the top results, and asks
    the local Ollama model for a short, spoken-friendly summary.
    Returns a plain string ready to be spoken/displayed by Sanju.
    """
    if not query.strip():
        return "What would you like me to search for?"

    results = _ddg_search(query)
    if not results:
        return f"I couldn't find anything on the web for {query}."

    combined = []
    for r in results:
        url     = r.get("href") or r.get("link") or ""
        title   = r.get("title", "")
        snippet = r.get("body", "")
        page_text = _fetch_page_text(url) if url else ""
        combined.append(f"Source: {title}\n{page_text or snippet}")

    context = "\n\n".join(combined)

    prompt = (
        f"Summarize the following web search results about \"{query}\" in "
        f"2 to 4 short spoken sentences. Be factual and natural, don't "
        f"mention 'sources' or 'according to the text' — just give the "
        f"answer directly like you looked it up yourself.\n\n{context}"
    )

    try:
        response = model_manager.chat(
            model=model_manager.CHAT_MODEL,
            messages=[{"role": "user", "content": prompt}],
            think=False,
        )
        summary = _strip_think(response["message"]["content"])
        return summary or f"I found results for {query} but couldn't summarize them."
    except Exception as e:
        print(f"[WebSearch] Summarize error: {e}")
        return f"I found some results for {query}, but had trouble summarizing them."